### ISSUE TITLE
srsran-project values.yaml: vlan_tag substituted by vlan_tag_cp and vlan_tag_up

### ISSUE THREAD

**Issue by hudouseko** [srsran/srsRAN_Project_helm#5]
Hi,
 I came across a minor issue, [values.yaml](https://github.com/srsran/srsRAN_Project_helm/blob/main/charts/srsran-project/values.yaml) default value for OFH VLAN is defined using `vlan_tag`:
```
    cells:
    - network_interface: enp1s0f0                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 70:b3:d5:e1:5b:06                              # RU MAC address.
      du_mac_addr: 80:61:5f:0d:df:aa                              # DU MAC address.
      vlan_tag: 5
```
Nevertheless currently (as per SRSRAN [configuration](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html) ) VLAN on OFH is defined using `vlan_tag_cp` and `vlan_tag_up`, not `vlan_tag` (which was used earlier). This is already correctly handled in [configmap.yml](https://github.com/srsran/srsRAN_Project_helm/blob/main/charts/srsran-project/templates/configmap.yml):
```
        {{- if .vlan_tag_up }}
        vlan_tag_up: {{ .vlan_tag_up }}
        {{- end }}
        {{- if .vlan_tag_cp }}
        vlan_tag_cp: {{ .vlan_tag_cp }}
        {{- end }}
```
Would be great to fix it in values.yml as well, but as a default is inbuilt in srs gnb itself and would be anyway typically overridden by local values.yml, I see this as quite minor issue.
